baseurl = "http://ilkka.io"
languageCode = "en-us"
title = "ilkka.io"
copyright = "Â© 2015 Ilkka Laukkanen. <a href=\"http://creativecommons.org/licenses/by-sa/4.0/\">Some rights reserved</a>."
theme = "ilkka.io"
canonifyurls = true
Paginate = 10

[params]
    author = "Ilkka"
    twitter = "ilkkalaukkanen"
    github = "ilkka"
